---
- name: Install required packages
  apt: "name={{item}} state=latest"
  with_items: "{{da_required_packages}}"

- name: Install pip packages
  pip: name={{item}}
  with_items: "{{da_required_pip}}"

- name: Check if docker package is installed
  command: "dpkg-query -l docker-engine"
  register: deb_check
  changed_when: False
  ignore_errors: True

- name: install docker
  shell: curl -sSL https://get.docker.com/ | sh
  when: deb_check.stderr.find('no packages found') != -1

- name: Get docker0 ip
  shell: echo $(ip addr | awk '/inet/ && /docker0/{sub(/\/.*$/,"",$2); print $2}')
  register: __host_ip_docker0

- name: Create etherpad repo dir
  file: "path={{da_ehterpad_repo_path}} state=directory owner={{da_user}} group={{da_user}}"

- name: Clone etherpad project
  git: "repo={{da_etherpad_repo}} dest={{da_ehterpad_repo_path}} force=yes"
  sudo_user: "{{da_user}}"

- name: Set etherpad conf file
  template: "src=settings.json.j2 dest={{da_ehterpad_repo_path}}/settings.json owner={{da_user}} group={{da_user}} mode=0644"

- name: Build docker image
  docker_image: "name={{da_docker_image_name}} path={{da_ehterpad_repo_path}} state=build"

- name: Run docker
  docker:
    name: "{{item.name}}"
    image: "{{da_docker_image_name}}"
    state: reloaded
    net: bridge
    # expose: "9001"
    ports:
    - "{{item.ports}}"
  with_items: "{{da_docker_instances}}"

- name: Run Seagull (docker monitoring)
  docker:
    name: seagull
    image: tobegit3hub/seagull
    state: reloaded
    volumes: "/var/run/docker.sock:/var/run/docker.sock"
    expose: 10086
    ports: "10086:10086"

- name: Run prometheus (docker monitoring)
  docker:
    name: prometheus
    image: prom/prometheus
    state: reloaded
    expose: 9090
    ports: "9090:9090"