---
- name: Install required packages
  apt: "name={{item}} state=latest"
  with_items: "{{da_required_packages}}"

- name: Create etherpad repo dir
  file: "path={{da_ehterpad_repo_path}} state=directory owner={{da_user}} group={{da_user}}"

- name: Clone etherpad project
  git: "repo={{da_etherpad_repo}} dest={{da_ehterpad_repo_path}} force=yes"
  sudo_user: "{{da_user}}"

- name: Set etherpad conf file
  template: "src=settings.json.j2 dest={{da_ehterpad_repo_path}}/settings.json owner={{da_user}} group={{da_user}} mode=0644"

# - name: Build docker image
#   docker_image: "name={{da_docker_image_name}} path={{ hellobaby_build_dir }} state=build
#   shell: "docker build -t {{da_user}}/etherpad-docker ."